// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxa4wflMMkA2brnG1w2f3oMZCNGb2lQBM',
    appId: '1:906633672260:web:c6f0cf55d807fd5ed4ae11',
    messagingSenderId: '906633672260',
    projectId: 'dating-3d7bb',
    authDomain: 'dating-3d7bb.firebaseapp.com',
    storageBucket: 'dating-3d7bb.firebasestorage.app',
    measurementId: 'G-79XKZ047V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInfKy1HrC4Tc8pL_-GgwDMB_aqkQ0yZk',
    appId: '1:906633672260:android:f6cbe08ef6350c05d4ae11',
    messagingSenderId: '906633672260',
    projectId: 'dating-3d7bb',
    storageBucket: 'dating-3d7bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBBmV8Yq1xg7RQShCcXh5V7ERz-HCBW78',
    appId: '1:906633672260:ios:2ff2c1eb68c8b692d4ae11',
    messagingSenderId: '906633672260',
    projectId: 'dating-3d7bb',
    storageBucket: 'dating-3d7bb.firebasestorage.app',
    iosBundleId: 'com.example.datingDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBBmV8Yq1xg7RQShCcXh5V7ERz-HCBW78',
    appId: '1:906633672260:ios:2ff2c1eb68c8b692d4ae11',
    messagingSenderId: '906633672260',
    projectId: 'dating-3d7bb',
    storageBucket: 'dating-3d7bb.firebasestorage.app',
    iosBundleId: 'com.example.datingDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxa4wflMMkA2brnG1w2f3oMZCNGb2lQBM',
    appId: '1:906633672260:web:122368d0fb1dc243d4ae11',
    messagingSenderId: '906633672260',
    projectId: 'dating-3d7bb',
    authDomain: 'dating-3d7bb.firebaseapp.com',
    storageBucket: 'dating-3d7bb.firebasestorage.app',
    measurementId: 'G-V1TETM08Z6',
  );
}
